import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h2>Welcome to Nextjs Stripe Integration Page</h2>
        <button className="mx-2 my-1 rounded-md bg-green-700 text-white px-2 py-1">
          <Link href={"/checkout-card"}>Go to Payment</Link>
        </button>
      </div>
    </div>
  );
}
